# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('nn.csv')

In [4]:
dataset

x         y         z  type
0      0.001601  0.002411  0.058439     1
1      0.001601  0.002411  0.052555     1
2      0.001601  0.002411  0.042748     1
3      0.003081  0.002123  0.102724     1
4      0.001601  0.002411  0.029016     1
...         ...       ...       ...   ...
18389 -0.084536  0.029911 -0.052045     2
18390 -0.070690  0.077925 -0.033627     2
18391 -0.054322  0.005287 -0.015010     2
18392 -0.009920  0.000539 -0.012780     2
18393 -0.000616  0.002563  0.056450     2

[18394 rows x 4 columns]

In [5]:
X = dataset.iloc[:, [1,2]].values #independent variables
y = dataset.iloc[:, -1].values # dependent variable

In [6]:
X

array([[ 0.00241087,  0.0584386 ],
       [ 0.00241087,  0.0525551 ],
       [ 0.00241087,  0.0427475 ],
       ...,
       [ 0.00528666, -0.0150102 ],
       [ 0.0005391 , -0.0127803 ],
       [ 0.00256338,  0.0564501 ]])

In [7]:
y

array([1, 1, 1, ..., 2, 2, 2])

In [8]:
print(y)

[1 1 1 ... 2 2 2]


### Encoding categorical data

Label Encoding the "Gender" column

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
#X[:, 2] = le.fit_transform(X[:, 2])

In [10]:
#print(X)

One Hot Encoding the "Geography" column

In [11]:
#from sklearn.compose import ColumnTransformer
#from sklearn.preprocessing import OneHotEncoder
#ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
#X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[ 0.00241087  0.0584386 ]
 [ 0.00241087  0.0525551 ]
 [ 0.00241087  0.0427475 ]
 ...
 [ 0.00528666 -0.0150102 ]
 [ 0.0005391  -0.0127803 ]
 [ 0.00256338  0.0564501 ]]


### Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [14]:
X_train

array([[-0.0180711 , -0.0942569 ],
       [-0.0134744 , -0.0521396 ],
       [ 0.00177823,  0.021016  ],
       ...,
       [ 0.00099774, -0.018973  ],
       [ 0.0272502 , -0.149982  ],
       [-0.0303687 , -0.181232  ]])

In [15]:
X_test

array([[ 0.00212082,  0.0109746 ],
       [ 0.00391942,  0.0597692 ],
       [-0.187806  , -0.113553  ],
       ...,
       [-0.00170145, -0.00449328],
       [-0.030503  , -0.151187  ],
       [-0.0194231 , -0.102997  ]])

### Feature Scaling

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [17]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [18]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [19]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [20]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [21]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [22]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
460/460 [==============================] - 0s 678us/step - loss: -2.5105 - accuracy: 0.4843
Epoch 2/100
460/460 [==============================] - 0s 687us/step - loss: -34.1993 - accuracy: 0.5017
Epoch 3/100
460/460 [==============================] - 0s 673us/step - loss: -140.8854 - accuracy: 0.5017
Epoch 4/100
460/460 [==============================] - 0s 651us/step - loss: -356.2418 - accuracy: 0.5017
Epoch 5/100
460/460 [==============================] - 0s 641us/step - loss: -700.5090 - accuracy: 0.5017
Epoch 6/100
460/460 [==============================] - 0s 672us/step - loss: -1185.2678 - accuracy: 0.5017
Epoch 7/100
460/460 [==============================] - 0s 680us/step - loss: -1821.7365 - accuracy: 0.5017
Epoch 8/100
460/460 [==============================] - 0s 654us/step - loss: -2614.5750 - accuracy: 0.5017
Epoch 9/100
460/460 [==============================] - 0s 677us/step - loss: -3573.0208 - accuracy: 0.5017
Epoch 10/100
460/460 [=======================

460/460 [==============================] - 0s 827us/step - loss: -886239.8125 - accuracy: 0.5017
Epoch 77/100
460/460 [==============================] - 0s 781us/step - loss: -918124.7500 - accuracy: 0.5017
Epoch 78/100
460/460 [==============================] - 0s 766us/step - loss: -950764.9375 - accuracy: 0.5017
Epoch 79/100
460/460 [==============================] - 0s 787us/step - loss: -984182.6250 - accuracy: 0.5017
Epoch 80/100
460/460 [==============================] - 0s 746us/step - loss: -1018387.2500 - accuracy: 0.5017
Epoch 81/100
460/460 [==============================] - 0s 747us/step - loss: -1053294.5000 - accuracy: 0.5017
Epoch 82/100
460/460 [==============================] - 0s 740us/step - loss: -1088957.8750 - accuracy: 0.5017
Epoch 83/100
460/460 [==============================] - 0s 739us/step - loss: -1125398.5000 - accuracy: 0.5017
Epoch 84/100
460/460 [==============================] - 0s 738us/step - loss: -1162695.3750 - accuracy: 0.5017
Epoch 85/100
460/4

**Solution**

In [23]:
print(ann.predict(sc.transform([[-0.00744156,-0.0472565]])))

[[1.]]


### Predicting the Test set results

In [24]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

In [25]:
y_pred

array([[ True],
       [ True],
       [ True],
       ...,
       [ True],
       [ True],
       [ True]])

In [26]:
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [1 1]
 [1 2]
 ...
 [1 1]
 [1 2]
 [1 2]]


### Making the Confusion Matrix

In [186]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1827    0]
 [1852    0]]


0.4966023375917369