**How many solutions are there in quadratic equations when roots are given**

In [6]:
import math

In [7]:
def solutions(a, b, c):
  X = (b**2) - (4*a*c)
  if X>0:
    return 2
  elif X == 0:
    return 1
  else:
    return 0


In [8]:
solutions(1,0,-1)

2

**ATM machines allow 4 or 6 digit PIN codes and PIN codes cannot contain anything but exactly 4 digits or exactly 6 digits. Your task is to create a function that takes a string and returns True if the PIN is valid and False if it's not.**

In [27]:
def is_valid_PIN(pin):
    if (len(pin)==4) or (len(pin)==6):
        return pin.isdigit()
    else:
        return False 

In [28]:
is_valid_PIN('a234')

False

In [29]:
is_valid_PIN('13456')

False

**Write a function that takes a year and returns its corresponding century.**

In [37]:
import math

def century_from_year(year):
    return (year+ 99) // 100   
    

In [41]:
century_from_year(1990)

20

**Create a function that takes in two lists and returns True if the second list follows the first list by one element, and False otherwise. In other words, determine if the second list is the first list shifted to the right by 1.**

In [46]:
def simon_says(lst1, lst2):
    if lst1[:-1] == lst2[1:]:
        return True
    else:
        return False
    

In [47]:
simon_says([1,2,3],[2,4,5])

False

In [48]:
simon_says([1, 2], [5, 1])

True

In [49]:
x = [1,2,3,4,5]
print(x[-1:])

[5]


In [50]:
y = [5,6,7,8,9]
print(y[1:])

[6, 7, 8, 9]


**You work in a toy car workshop, and your job is to build toy cars from a collection of parts. Each toy car needs 4 wheels, 1 car body, and 2 figures of people to be placed inside. Given the total number of wheels, car bodies and figures available, how many complete toy cars can you make?**

In [56]:
import math
def cars(wheels, bodies, figures):
    A = math.floor(wheels/4)
    B = bodies
    C = math.floor(figures/2)
    list1 = [A,B,C]
    return min(list1)

In [57]:
cars(43, 15, 87)

10

**Create a function that returns the thickness (in meters) of a piece of paper after folding it n number of times. The paper starts off with a thickness of 0.5mm.**

In [100]:
def num_layers(n):
    x = 0.5 * 2 **n /1000
    if x == 0:
        return "0.0005m"
    else:
        return str(x) + "m"
    

In [101]:
num_layers(0)

'0.0005m'

**Write a function that searches a list of names (unsorted) for the name "Bob" and returns the location in the list. If Bob is not in the array, return -1**

In [105]:
def find_bob(names):
    if 'Bob' in names:
        return names.index('Bob')
    else:
        return -1
    
    

In [106]:
find_bob(["Jimmy", "Layla", "James"])

-1

In [107]:
find_bob(["Jimmy", "Layla", "Bob"])

2

**Write a function that stutters a word as if someone is struggling to read it. The first two letters are repeated twice with an ellipsis ... and space after each, and then the word is pronounced with a question mark ?**


In [123]:
def stutter(word):
    new_word= word[:2] + "... " + word[:2] + "... " + word + "?"
    return new_word
    
print(stutter("increasing"))
print(stutter("adventures"))
print(stutter("am"))

in... in... increasing?
ad... ad... adventures?
am... am... am?


**Given an unsorted list, create a function that returns the nth smallest element (the smallest element is the first smallest, the second smallest element is the second smallest, etc).**

In [7]:
def nth_smallest(lst, n):
    if n > len(lst):
        return None
    else:
        return sorted(lst)[n-1]
    
        
       

In [8]:
nth_smallest([1,2,3,4], 1)

1

**Create a function that counts how many characters make up a rectangular shape. You will be given a list of strings**

In [308]:
def count_characters(lst):
    count = 0
    for i in lst:
        count += len(i)
    return count
    
        

In [309]:
count_characters([
  "22222222",
  "22222222",
]) 

16

In [310]:
count_characters(["------------------"])

18

In [311]:
count_characters(["######"])

6

**Create a function that finds the maximum range of a triangle's third edge, where the side lengths are all integers.**

In [285]:
def next_edge(side1, side2):
    third_edge = (side1 + side2) -1
    if third_edge > 0:
        return third_edge

In [31]:
next_edge(7,5)

11

**Luke Skywalker has family and friends. Help him remind them who is who. Given a string with a name, return the relation of that person to Luke.**

In [37]:
dic={

"Darth Vader":"father",

"Leia":"sister",
  
"Han": "brother in law",

"R2D2": "droid"
}

def relation_to_luke(name): 

  name=dic.get(name) 
  
  return ("Luke, I am your {}.".format(name))

In [38]:
relation_to_luke("Darth Vader")

'Luke, I am your father.'

In [39]:
relation_to_luke("Leia")

'Luke, I am your sister.'

**Create a function that returns the sum of all even elements in a 2D matrix.**

In [65]:
import numpy as np
import sys

def sum_of_evens(lst):
    single = []
    for i in lst:
        for j in i:
            single.append(j)
    s = 0
    for k in single:
        if k % 2 == 0:
            s += k
    return s
    
   
           

In [67]:
sum_of_evens([
  [1, 0, 2],
  [5, 5, 7],
  [9, 4, 3]
])

6

## SODUKO solver

In [106]:
grid = [[5,3,0,0,7,0,0,0,0],
        [6,0,0,1,9,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,7,9]
    
]

In [132]:
import numpy as np
print(np.matrix(grid))

[[0 3 0 0 7 0 0 0 0]
 [6 0 0 1 0 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 0 0]]


In [133]:
def possible(y,x,n):
    global grid
    for i in range(0,9):
        if grid[y][i] == n:
            return False
    for i in range(0,9):
        if grid [x][i] == n:
            return False
    x0 = (x // 3) * 3
    y0 = (y // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if grid[y0+i][x0+j] == n :
                return False
    
    return True
        

In [151]:
possible(4,4,5)

True

In [152]:
def solve():
    global grid
    for y in range(9):
        for x in range(9):
            if grid[y][x] == 0:
                for n in range(1,10):
                    if possible(y,x,n):
                        grid[y][x] = n
                        solve()
                        grid[y][x] = 0
                return 
    np.matrix(grid)
    input("More?")

In [153]:
solve()

In [154]:
grid = [[0,3,0,0,7,0,0,0,0],
        [6,0,0,1,0,5,0,0,0],
        [0,9,8,0,0,0,0,6,0],
        [8,0,0,0,6,0,0,0,3],
        [4,0,0,8,0,3,0,0,1],
        [7,0,0,0,2,0,0,0,6],
        [0,6,0,0,0,0,2,8,0],
        [0,0,0,4,1,9,0,0,5],
        [0,0,0,0,8,0,0,0,0]
    ]
solve()


In [155]:
solve()



**replace vowel with given character**

In [160]:
def vow_replace(word, vowel):
    v = "aeiou" or "AEIOU"
    for i in word:
        if i in v:
            txt = word.replace(i,vowel)
    return txt



In [161]:
vow_replace("apples and bananas", "u")

'upples und bununus'

In [162]:
vow_replace("cheese casserole", "o")

'chooso cassorolo'

**Compare two words**

In [163]:
def is_anagram(s1, s2):
    u1 = []
    u2 = []
    for i in s1:
        up = sorted(i.upper())
        u1.append(up)
    for j in s2:
        sp = sorted(j.upper())
        u2.append(sp)
        if u1 == u2:
            return True
        else:
            return False



In [164]:
is_anagram("cristian", "Cristina")

False

In [165]:
is_anagram("Nope", "Note")

False

**eate a function that takes a number as an argument and returns "Fizz", "Buzz" or "FizzBuzz".**

In [174]:
def fizz_buzz(n):
    if n % 3 ==0 and n % 5 == 0:
        return "FizzBuzz"
    elif n % 3 == 0:
        return "Fizz"
    elif n % 5 == 0:
        return "Buzz"
    else:
        return str(n)

In [175]:
fizz_buzz(5)

'Buzz'

In [176]:
fizz_buzz(1)

'1'

In [177]:
fizz_buzz(15)

'FizzBuzz'

**Lowercase and Uppercase Map**

In [180]:
def mapping(letters):
    return {item:item.upper() for item in letters}

In [181]:
mapping(["a", "v", "y", "z"])

{'a': 'A', 'v': 'V', 'y': 'Y', 'z': 'Z'}

**Write a function that returns the lexicographically first and lexicographically last rearrangements of a string. Output the results in the following manner:**

In [209]:
def first_and_last(s):
    #lst1 = sorted(s)
    #A = ''.join(lst1)
    #return A
    lst2 = ""
    lst2 = (i + lst for i in s)
    return lst2

In [210]:
first_and_last("marmite")

<generator object first_and_last.<locals>.<genexpr> at 0x7f09a5c5c850>

In [219]:
def first_and_last(s):
    lst2 = ""
    for i in s:
        lst2 = i + lst2
        result = A.append(lst2)
    return result

In [220]:
first_and_last("marmite")

In [221]:
def first_and_last(s):
    s = list(s)
    s.sort()
    return ["".join(s), "".join(reversed(s))]

In [222]:
first_and_last("marmite")

['aeimmrt', 'trmmiea']

In [224]:
first_and_last("scoop")

['coops', 'spooc']

**Given the radius of a circle and the area of a square, return True if the circumference of the circle is greater than the square's perimeter and False if the square's perimeter is greater then the circumference of the circle.**

In [313]:
import math
def circle_or_square(rad, area):
    c_c = 2 * math.pi * rad
    p_s = 4 * math.sqrt(area)
    if c_c > p_s:
        return True
    else:
        return False
    

In [314]:
circle_or_square(16, 625)

True

In [315]:
circle_or_square(5, 100)

False

**Create a function, that will for a given a, b, c, do the following:**

- Add a to itself b times.
- Check if the result is divisible by c.

In [326]:
def abcmath(a, b, c):
    num_1 = (a + a) * b
    if num_1 % c == 0:
        return True
    else:
        return False

In [327]:
abcmath(5, 2, 1)

True

In [328]:
abcmath(1, 2, 3)

False

In [329]:
abcmath(42, 5, 10)

True

**Create a function that takes two numbers and a mathematical operator + - / * and will perform a calculation with the given numbers.**

In [332]:
def calculator(num1, operator, num2):
    if operator == "/" and num2 == 0:
        return "Can't divide by 0!"
    if operator == "+":
        return num1 + num2
    if operator == "-":
        return num1 - num2
    if operator == "*":
        return num1 * num2
    if operator == "/":
        return num1 / num2

In [333]:
calculator(4, "/", 2)

2.0

In [338]:
def calculator(num1, operator, num2):
    if operator == "/" and num2 == 0:
        return "Can't divide by 0!"
    else:
        return eval('num1' + operator + 'num2')

In [339]:
calculator(4, "/", 2)

2.0

**A group of friends have decided to start a secret society. The name will be the first letter of each of their names, sorted in alphabetical order.
Create a function that takes in a list of names and returns the name of the secret society.**

In [381]:
def society_name(friends):
    return "".join([i[0] for i in sorted(friends)])

In [382]:
society_name(["Adam", "Sarah", "Malcolm"])

'AMS'

In [383]:
def society_name(friends):
    name = ""
    friends.sort()
    for i in friends:
        name += i[0]
    return name

In [384]:
society_name(["Adam", "Sarah", "Malcolm"])

'AMS'

In [385]:
society_name(["Adam", "Sarah", "Malcolm"])

'AMS'

**Create a function to convert a list of percentages to their decimal equivalents.**

In [472]:
def convert_to_decimal(perc):
    return [float(x.strip("%"))/100 for x in perc ]

In [473]:
convert_to_decimal(["1%", "2%", "3%"])

[0.01, 0.02, 0.03]

**Create a function that takes a list of integers and removes the smallest value.**

In [432]:
def remove_smallest(t):
    t.remove(min(t))
    return t
    

In [433]:
remove_smallest([1, 2, 3, 4, 5] )

[2, 3, 4, 5]

**Write a function that takes a string (the message) and returns the total number of times the button is pressed.**

In [436]:
def how_many_times(msg):
    return sum(ord(i) -96 for i in msg)
    

In [437]:
how_many_times("qudusayo")

123

**The Code tab has code which attempts to add a clone of a list to itself. There is no error message, but the results are not as intended. Can you fix the code?**

In [474]:
def clone(lst):
    lst.append(lst[:])
    return lst

In [475]:
clone(["x", "y"])

['x', 'y', ['x', 'y']]

**Scrabble Hand**

In [490]:
def maximum_score(tile_hand):
    count = 0
    for i in tile_hand:
        count += i.get("score")
    return count

In [491]:
maximum_score([
  { "tile": "N", "score": 1 },
  { "tile": "K", "score": 5 },
  { "tile": "Z", "score": 10 },
  { "tile": "X", "score": 8 },
  { "tile": "D", "score": 2 },
  { "tile": "A", "score": 1 },
  { "tile": "E", "score": 1 }
])



28

In [487]:
maximum_score =([
  { "tile": "B", "score": 2 },
  { "tile": "V", "score": 4 },
  { "tile": "F", "score": 4 },
  { "tile": "U", "score": 1 },
  { "tile": "D", "score": 2 },
  { "tile": "O", "score": 1 },
  { "tile": "U", "score": 1 }
]) 

x = 0
for i in maximum_score:
    
    x += i.get("score") 
print(x)

15


**Given a list of numbers and a value n, write a function that returns the probability of choosing a number greater than or equal to n from the list. The probability should be expressed as a percentage, rounded to one decimal place.**

In [567]:
def probability(lst, n):
    total_number = len(lst)
    root = []
    for i in lst:
        if i >= n :
            root.append(i)
    #return len(root)
    result = (len(root) /total_number) * 100
    return round(result,1)
    

In [568]:
probability([7, 4, 17, 14, 12, 3], 16)

16.7

In [569]:
probability([4, 6, 2, 9, 15, 18, 8, 2, 10, 8], 6)

70.0

In [570]:
probability([5, 1, 8, 9], 6)

50.0

**Create a function that takes an integer and returns a list from 1 to the given number, where:**

1. If the number can be divided evenly by 4, amplify it by 10 (i.e. return 10 times the number).
2. If the number cannot be divided evenly by 4, simply return the number.

In [641]:
def amplify(num):
    lst = []
    for i in range(1,num+1):
        lst.append(i)
        lst1 = []
        for j in lst:
            if j % 4 == 0:
                lst1.append(j * 10)
            else:
                lst1.append(j)
            
    return lst1
    

In [642]:
amplify(5)

[1, 2, 3, 40, 5]

In [643]:
amplify(9)

[1, 2, 3, 40, 5, 6, 7, 80, 9]

In [644]:
amplify(10)

[1, 2, 3, 40, 5, 6, 7, 80, 9, 10]